"""
The paginated results of an `chronicleProducers` query.
See [about queries](/guides/types/#queries) for details on how "connection" and "edge" types are used with pagination.
"""
type ChronicleProducerConnection {
    """The resulting collection of chronicle producer edges."""
    edges: [ChronicleProducerEdge!]!
    """Pagination information for the resulting edges."""
    pageInfo: PageInfo!
    """The total count of chronicle producers matching the query, across all pages."""
    totalCount: Int!
}

"""
The pairing of an ChronicleProducer with its query cursor.
See [about queries](/guides/types/#queries) for details on how "connection" and "edge" types are used with pagination.
"""
type ChronicleProducerEdge {
    """
    Information about a particular ChronicleProducer.
    """
    node: ChronicleProducer!
    """
    The cursor to use with the Query `chronicleProducers` field `after` argument.
    """
    cursor: String!
}