"""
FilterEventChronicleInput filters EventChronicles based on criteria described below.
Only one field should be provided per Filter object unless using an operator (`and` `or` `not`) as specified below.
"""
input FilterEventChronicleInput {
    """
    If provided, specifies filters that work against the `id` of the `EventChronicle`.
    """
    id: FilterIDInput
    """
    If provided, specifies filters that work against the `name` of the `EventChronicle`.
    """
    name: FilterStringInput
    """
    If provided, specifies filters that work against the `chronicleProducer` ID of the `EventChronicle`.
    """
    chronicleProducerId: FilterIDInput
    """
    If provided, specifies filters that work against the `timestamp` of the `EventChronicle`.
    """
    timestamp: FilterDateTimeOffsetInput
    """
    If provided, specifies filters that work against the `timezone` of the `EventChronicle`.
    """
    timezone: FilterStringInput
    """
    If provided, specifies filters that work against the `priority` of the `EventChronicle`.
    """
    priority: FilterStringInput
    """
    If provided, specifies filters that work against the `status` of the `EventChronicle`.
    """
    status: FilterStringInput
    """
    If provided, specifies filters that work against the `validation` of the `EventChronicle`.
    """
    validation: FilterChronicleValidationStatusInput
    """
    If provided, specifies filters that work against the `labels` of the `EventChronicle`.
    """
    labels: FilterStringListInput
    """
    If provided, specifies filters that work against the `locations` of the `EventChronicle`.
    """
    locations: FilterStringListInput
    """
    If provided, specifies filters that work against the `activityChronicles` IDs of the `EventChronicle`.
    """
    activityChronicleIds: FilterIDListInput
    """
    If provided, an event must pass all filters in this list to match the current filter.
    """
    and: [FilterEventChronicleInput!]
    """
    If provided, an event must pass at least one of the filters in this list to match the current filter.
    """
    or: [FilterEventChronicleInput!]
    """
    If provided, an event may not match this filter to match the current filter.
    """
    not: FilterEventChronicleInput
}